select top 1000 * from dbo.customer_behavior_cleaned

--1.what is the revnue generated by male vs female customer

select gender , sum(purchase_amount) as revenue
from dbo.customer_behavior_cleaned
group by(gender)

--2.which customer used a discount but still sepnt more than the average purchase amount
select customer_id, purchase_amount
from dbo.customer_behavior_cleaned
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from dbo.customer_behavior_cleaned)

--3.which are top 5 products with highest average review rating
select top 5 item_purchased, avg(review_rating) as average_product_rating
from customer_behavior_cleaned
group by item_purchased
order by avg(review_rating) desc

--4.Compare the average Purchase amount between Standard and Express shipping
select avg(purchase_amount),
shipping_type from dbo.customer_behavior_cleaned
where shipping_type in ('Standard','Express')
group by shipping_type

--5.Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customer,
avg(purchase_amount) as avg_spent,
sum(purchase_amount) as total_revenue
from dbo.customer_behavior_cleaned
group by subscription_status
order by total_revenue, avg_spent desc

--6. What are top 3 most purchased in each category

with cte as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from dbo.customer_behavior_cleaned
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders 
from cte
where item_rank<=3

--7. Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from dbo.customer_behavior_cleaned
where previous_purchases > 5
group by subscription_status

--8.what is revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from dbo.customer_behavior_cleaned
group by age_group
order by total_revenue desc
